version: "3"

volumes:
    db-data:
        external: false

services: 
    app:
        build: 
            context: ./src
            dockerfile: Dockerfile
        volumes:
            - ./src:/var/www/
            - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - 9000
        container_name: app
        restart: unless-stopped
        networks: 
            - app-network
    
    nginx-web:
        image: nginx:alpine
        container_name: nginx-web
        restart: unless-stopped
        ports:
            - 82:80
            - 443:443
        volumes:
            - ./src:/var/www/
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx/conf.d/:/etc/nginx/conf.d
        depends_on: 
            - app
        networks:
            - app-network
    
    database:
        image: mariadb:latest
        container_name: database
        restart: unless-stopped
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
        env_file: .env
        networks:
            - app-network
        depends_on: 
            - nginx-web

networks:
    app-network:
        driver: bridge
